build-development:
	docker build -t client-development -f Dockerfile-development .

build-local:
	docker build -t client-local -f Dockerfile-production .

build-production:
	docker build -t client-production -f Dockerfile-production .