build-development:
	docker build -t client-development .

build-local:
	docker build -t moonstocks-client-local -f Dockerfile.local .

build-production:
	docker build -t moonstocks-client-production -f Dockerfile.production .