version: '3'
services:
  client-production:
    image: client-production
    container_name: production
    build: ./client
    restart: unless-stopped
    ports:
      - '80:3000'
    networks:
      - moonstocks-production
networks:
  moonstocks-production:
    driver: bridge