version: "3"
services:
  client:
    image: development
    build: ./client/
    environment:
      - REACT_APP_SERVER_URL=${SERVER_URL}
    stdin_open: true
    # ports: 
    #   - "3000:3000"
    networks:
      - moonstocks
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  server:
    image: server
    build: ./server/
    environment:
      - MONGO_URL=${MONGO_URL}
      - ENV=${ENV}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    # ports:
    #   - "5000:5000"
    networks:
      - moonstocks
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    networks:
      - moonstocks
    volumes:
      - mongo-data:/data/db
  nginx:
    restart: unless-stopped
    depends_on:
      - client
      - server
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.development
    ports:
      - 8080:80
    networks:
      - moonstocks
networks:
  moonstocks:
    driver: bridge
volumes:
  mongo-data:
    driver: local
