build-development:
	docker build -t server-development .

build-local:
	docker build -t server-local -f Dockerfile.local .

build-production:
	docker build -t server-production -f Dockerfile.production .