build-development:
	docker build -t nginx-development -f Dockerfile-development .

build-local:
	docker build -t nginx-local -f Dockerfile-local .

build-production:
	docker build -t nginx-production -f Dockerfile-production .